### ISSUE TITLE
[Bug]: License not working with NLF files

### ISSUE THREAD

**Issue by wolftales** [NetApp/terraform-provider-netapp-ontap#69]
### Terraform Core Version

1.6.3

### ONTAP Provider Version

1.0.0

### Affected Resource(s)

Netapp-ontap_cluster_licenseing_license_resource

```
resource "netapp-ontap_cluster_licensing_license_resource" "cluster_licensing_license" {
  cx_profile_name = "redshirt"
  keys           = [file("NLF-4034389062-EE.txt"),file("NLF-4082368507-EE.txt")]
  # keys           = [file("NLF-4034389062-EE.txt")]
}
```

### Expected Behavior

Apply licenses for both nodes within a cluster

### Actual Behavior

provider crashed when adding 2 license files

### Relevant Error/Panic Output Snippet

```shell
A single entry works, however when trying to add 2 files for 2 sims results in this crash:


ken@ubuntu:netapp-ontap$ terraform apply
netapp-ontap_cluster_licensing_license_resource.cluster_licensing_license: Refreshing state... [id=nfs]
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-netapp-ontap_v1.0.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 6 [running]:
github.com/netapp/terraform-provider-netapp-ontap/internal/provider.(*ClusterLicensingLicenseResource).Read(0xc00053c380, {0xdd13a0, 0xc0002b1050}, {{{{0xdd57f0, 0xc0003c2360}, {0xb9c140, 0xc0003c2180}}, {0xdd8868, 0xc0005943c0}}, 0xc000188798, ...}, ...)
        github.com/netapp/terraform-provider-netapp-ontap/internal/provider/cluster_licensing_license_resource.go:187 +0x5e7
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0000efce0, {0xdd13a0, 0xc0002b1050}, 0xc0002b10e0, 0xc0001dd5f8)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_readresource.go:101 +0x617
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0000efce0, {0xdd13a0?, 0xc0002b0f00?}, 0xc00053c200)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/proto6server/server_readresource.go:55 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000178500, {0xdd13a0?, 0xc0002b0570?}, 0xc00027dda0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:749 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xc558a0?, 0xc000178500}, {0xdd13a0, 0xc0002b0570}, 0xc000569810, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:386 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00016e1e0, {0xdd6c18, 0xc00040e1a0}, 0xc0002afc20, 0xc00014fdd0, 0x1274a50, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc00016e1e0, {0xdd6c18, 0xc00040e1a0}, 0xc0002afc20, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.3/server.go:958 +0x15c

Error: The terraform-provider-netapp-ontap_v1.0.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
```


### Terraform Configuration Files

```
terraform {
  required_providers {
    netapp-ontap = {
      source = "NetApp/netapp-ontap"
      version = "1.0.0"
    }
  }
  required_version = ">= 1.6.3"
}

provider "netapp-ontap" {
  connection_profiles = [
    {
      name = "redshirt"
      hostname = var.hostname
      username = var.username
      password = var.password
      validate_certs = var.validate_certs
    },
  ]
}

resource "netapp-ontap_cluster_licensing_license_resource" "cluster_licensing_license" {
  cx_profile_name = "redshirt"
  keys           = [file("NLF-4034389062-EE.txt"),file("NLF-4082368507-EE.txt")]
  # keys           = [file("NLF-4034389062-EE.txt")]
}
```

### Steps to Reproduce

add a second file lookup to add to the "keys" parameter

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

**Comment by carchi8py** [comment]
@wolftales we'll check this out in the morning.

**Comment by wolftales** [comment]
I tried to recreate this and it is working now. Here is the resource entry I'm using with the 2 files:

```
resource "netapp-ontap_cluster_licensing_license_resource" "cluster_licensing_license" {
  cx_profile_name = var.cluster_name
  keys            = [file("NLF-4034389062-EE.txt"), file("NLF-4082368507-EE.txt")]
}
```

I have TF_LOG=DEBUG & TF_LOG_PATH=logs.txt ready if it happens again.

**Comment by carchi8py** [comment]
@wolftales did the licenses take?

I was reviewing our testing and we only tested with License key. We didn't test with a licenses file .

**Comment by wolftales** [comment]
Yes it did, for both vsims & serial-nums with the above input.  

I've reset this a couple of times and haven't had a similar crash issue.  I'm inclined to think something else is going on. Shall we close this? I'll re-open if needed.

Here is the ONTAP `license show` command output:

```
redshirt::> license show
  (system license show)

Serial Number: 4034389062
Owner: redshirt-02
Installed License: Enterprise Edition
Capacity: 910TB
Package           Type     Description           Expiration
----------------- -------- --------------------- -------------------
NFS               capacity NFS License           -
CIFS              capacity CIFS License          -
iSCSI             capacity iSCSI License         -
FCP               capacity FCP License           -
SnapRestore       capacity SnapRestore License   -
SnapMirror        capacity SnapMirror License    -
FlexClone         capacity FlexClone License     -
SnapVault         capacity SnapVault License     -
SnapManagerSuite  capacity SnapCenter License    -
TPM               capacity Trusted Platform Module License 
                                                 -
VE                capacity Volume Encryption License 
                                                 -
SnapMirror_Sync   capacity SnapMirror Synchronous License 
                                                 -
NVMe_oF           capacity NVMe-oF License       -
S3                capacity S3 License            -
S3_SnapMirror     capacity S3 SnapMirror License -

Serial Number: 4082368507
Owner: redshirt-01
Installed License: Enterprise Edition
Capacity: 910TB
Package           Type     Description           Expiration
----------------- -------- --------------------- -------------------
NFS               capacity NFS License           -
CIFS              capacity CIFS License          -
iSCSI             capacity iSCSI License         -
FCP               capacity FCP License           -
SnapRestore       capacity SnapRestore License   -
SnapMirror        capacity SnapMirror License    -
FlexClone         capacity FlexClone License     -
SnapVault         capacity SnapVault License     -
SnapManagerSuite  capacity SnapCenter License    -
TPM               capacity Trusted Platform Module License 
                                                 -
VE                capacity Volume Encryption License 
                                                 -
SnapMirror_Sync   capacity SnapMirror Synchronous License 
                                                 -
NVMe_oF           capacity NVMe-oF License       -
S3                capacity S3 License            -
S3_SnapMirror     capacity S3 SnapMirror License -
30 entries were displayed.

redshirt::> 
```

**Comment by carchi8py** [comment]
I"ll go ahead and close it. I'm going to take your example and add it to the documentation so we have an example with the 28 character string and the NFL file for users.
